const data = {
  products: [
    {
      productName: "Asymmetric neckline blouse",
      slug: "asymmetric_neckline_blouse",
      image: "/images/image1.png",
      price: 93.51,
      countInStock: 10,
      tax: 5.0,
      shipping: 2.29,
    },
    {
      productName: "Paperbag denim shorts",
      slug: "paperbag_denim_shorts",
      image: "/images/image2.png",
      price: 103.0,
      countInStock: 10,
      tax: 5.0,
      shipping: 2.29,
    },
    {
      productName: "Waist straight Slouchy jeans",
      slug: "Waist_straight_Slouchy_jeans",
      image: "/images/image3.png",
      price: 41.0,
      countInStock: 10,
      tax: 5.0,
      shipping: 2.29,
    },
    {
      productName: "Asymmetric neckline blouse",
      slug: "asymmetric_neckline_blouse1",
      image: "/images/image1.png",
      price: 45.5,
      countInStock: 10,
      tax: 5.0,
      shipping: 2.29,
    },
    {
      productName: "Paperbag denim shorts",
      slug: "paperbag_denim_shorts1",
      image: "/images/image2.png",
      price: 200.2,
      countInStock: 10,
      tax: 5.0,
      shipping: 2.29,
    },
    {
      productName: "Waist straight Slouchy jeans",
      slug: "Waist_straight_Slouchy_jeans1",
      image: "/images/image3.png",
      price: 99.99,
      countInStock: 10,
      tax: 5.0,
      shipping: 2.29,
    },
    {
      productName: "Asymmetric neckline blouse",
      slug: "asymmetric_neckline_blouse2",
      image: "/images/image1.png",
      price: 100.99,
      countInStock: 10,
      tax: 5.0,
      shipping: 2.29,
    },
    {
      productName: "Paperbag denim shorts",
      slug: "paperbag_denim_shorts2",
      image: "/images/image2.png",
      price: 50.09,
      countInStock: 10,
      tax: 5.0,
      shipping: 2.29,
    },
    {
      productName: "Waist straight Slouchy jeans",
      slug: "Waist_straight_Slouchy_jeans2",
      image: "/images/image3.png",
      price: 99.99,
      countInStock: 10,
      tax: 5.0,
      shipping: 2.29,
    },
    {
        productName: "Asymmetric neckline blouse",
        slug: "asymmetric_neckline_blouse3",
        image: "/images/image1.png",
        price: 100.99,
        countInStock: 10,
        tax: 5.0,
        shipping: 2.29,
      },
  ],
};
export default data;
